### ISSUE TITLE
README

### ISSUE THREAD

**Issue by loretoparisi** [young-geng/koala_data_pipeline#1]
Please provide a readme with instructions how to train and how to diff pretrained Koala model weights against Llama weights.

**Comment by young-geng** [comment]
This is this not the training and serving repo. The main repo is [EasyLM](https://github.com/young-geng/EasyLM).

**Comment by loretoparisi** [comment]
> This is this not the training and serving repo. The main repo is [EasyLM](https://github.com/young-geng/EasyLM).

ok thanks  I would link the koala md 

https://github.com/young-geng/EasyLM/blob/main/docs/koala.md

Thank you cannot wait to try it out!
