### ISSUE TITLE
Can you provide some insights on the data?

### ISSUE THREAD

**Issue by pGit1** [young-geng/koala_data_pipeline#2]
@young-geng  I've been waiting for this release and thought it would be amazing! I am not disappointed! This is an amazing contribution!

I have a few questions questions about your training data specifically and in general:

1. You state that you use these datasets in the blog post (https://bair.berkeley.edu/blog/2023/04/03/koala/):

-  ShareGPT (1)
- Human ChatGPT Comparison Corpus (HC3) (2)
- Open Instruction Generalist (OIG) (3)
- Stanford Alpaca (4)
- Anthropic HH (5)
- OpenAI WebGPT (6)
- OpenAI Summarization (7)

However in this repo (**excluding** hardcoded data) you only show 4 python files for preprocessing code. Any reason for this?

2. Of the 7 datasets I outlined above that are referenced in your blog, which of the 7 does ```process_chat_data.py``` correspond to? Also the **most important** of all this data, i.e. ShareGPT data, seems to be missing. Is this intentional due to Google using it for Bard? :disappointed: 

3. Since you have already processed these datasets do you plan on releasing them similar to the Alpaca dataset release? Either on this repo, EasyLLM, or Hugging Face? That would be **super helpful**! :smile: 

4. My last question is about formatting data for Koala and LLMs in general. Do all the resulting jsons from the processing this repo does result in data with the same structure as the Alpaca dataset or are all datasets processed differently? Is this the same/different file structure desirable or necessary?

**Comment by young-geng** [comment]
The webgpt, openai summary and anthropic hh datasets are all processed in the `create_hf_data_v2.py`. The HC3 data is  processed together with OIG via the `process_oig_data.py`. Hence this repo includes all the processing scripts we used to create the Koala training dataset.

Regarding releasing the data, we don't own the copyright of the scraped ShareGPT data. For other open source datasets, they are directly downloaded from the corresponding huggingface datasets repo.

Finally, the resulting dataset is in very different structures compared to Alpaca. You can take a look at the [dataset documentation of EasyLM](https://github.com/young-geng/EasyLM/blob/main/docs/dataset.md) to get a sense of the format.

**Comment by pGit1** [comment]
I think this all makes sense! So the important thing in LLM training is that regardless of input format, we need a general text processor that can produce "tokens" of the relevant inputs. The format is necessary to control but it is more important to make sure can ingest the data and tokenize appropriately. Is this correct?

If so, one last question. Does EasyLLM support masking loss, i.e. ignoring input tokens and only compute loss on designated "output" tokens? Looks like it might starting here from what I gather: 
https://github.com/young-geng/EasyLM/blob/3a8b2a0b98f2c50cf982ca68633203f523ccf83e/EasyLM/data.py#L77

**Comment by young-geng** [comment]
Yes, EasyLM does support that, and that's what we used to train Koala. You might want to check out the [text processor section of EasyLM documentation](https://github.com/young-geng/EasyLM/blob/main/docs/dataset.md#text-processor).

**Comment by pGit1** [comment]
I read this section but its not clear to me then how I could train on all the datasets (whether json or hugginface) given this example since you have to specify the dataset type and "fields" are going to the text processor. I know I am reading this incorrectly but just trying to make sense of everything

**Comment by pGit1** [comment]
@young-geng Either way I think I understand why you are getting at in either case I can close the issue now. Thanks for taking time to answer and do this awesome work! :1st_place_medal:
