### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by ehartford** [young-geng/koala_data_pipeline#3]
I would like to request the dataset so that I can finetune it myself and build 30b and 65b weights.

**Comment by young-geng** [comment]
Unfortunately, we don't own the copyright for the ShareGPT data, so we cannot release ourselves. For the open source dataset, you can download them directly from Huggingface datasets.

**Comment by ehartford** [comment]
ok.. but, in that case, can you please provide the id's of the ShareGPT questions you used in your data, so that I Can download them myself from ShareGPT?
I would like to recreate your training dataset.  What information do I need in order to do that?
